name: Build on Issue Closed

on:
  issues:
    types: [closed]


permissions:
  actions: read
  contents: read
  issues: write

jobs:
  deprovision:
    name: Deprovisioning Staging environment
    if: contains(github.event.issue.labels.*.name, 'staging')
    runs-on: ubuntu-latest
    environment: STAGE

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Extract Artifact ID
      id: extract-id
      run: |
        echo "Extracting Artifact ID from issue body..."
        ARTIFACT_ID=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=Artifact ID: ).*')
        echo "ARTIFACT_ID=${ARTIFACT_ID}" >> $GITHUB_ENV

    - name: Download Artifact
      run: |
        echo "Downloading artifact..."
        echo "curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip -o artifact.zip"
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip -o artifact.zip
        unzip artifact.zip -d artifact
        cd artifact/terraform
        terraform init
        terraform destroy -auto-approve -var 'sql_admin_password=${{ secrets.SA_PASSWORD }}'
